apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: optiprism
spec:
  secretName: secret-tls
  renewBefore: 240h
  duration: 2160h
  commonName: demdxx.optiprism.io
  dnsNames:
    - demdxx.optiprism.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer