use crate::store::intention::Intention;

pub struct Coefficients {
    pub abandon_cart: f64,
    pub cart_completion: f64,
    pub discover: f64,
    pub search_for_product: f64,
    pub go_to_index: f64,
    pub store_navigation_quality: f64,
    pub bounce_rate: f64,
    pub global_bounce_rate: f64,
    pub buy_multiple_products: f64,
    pub search_quality: f64,
    pub view_product_to_buy: f64,
    pub refund: f64,
    pub product_rating: f64,
}

pub fn make_coefficients(intention: &Intention) -> Coefficients {
    match intention {
        Intention::BuyCertainProduct(_) => Coefficients {
            abandon_cart: 0.1,
            cart_completion: 0.9,
            discover: 0.7,
            search_for_product: 0.0,
            go_to_index: 0.1,
            store_navigation_quality: 0.9,
            bounce_rate: 0.1,
            global_bounce_rate: 0.1,
            buy_multiple_products: 0.0,
            search_quality: 0.9,
            view_product_to_buy: 0.5,
            refund: 0.0,
            product_rating: 0.9,
        },
        Intention::BuyAnyProduct => Coefficients {
            abandon_cart: 0.1,
            cart_completion: 0.9,
            discover: 0.7,
            search_for_product: 0.0,
            go_to_index: 0.1,
            store_navigation_quality: 0.9,
            bounce_rate: 0.1,
            global_bounce_rate: 0.1,
            buy_multiple_products: 0.1,
            search_quality: 0.9,
            view_product_to_buy: 0.5,
            refund: 0.0,
            product_rating: 0.9,
        },
        Intention::JustBrowse => Coefficients {
            abandon_cart: 0.1,
            cart_completion: 0.9,
            discover: 0.7,
            search_for_product: 0.0,
            go_to_index: 0.1,
            store_navigation_quality: 0.9,
            bounce_rate: 0.1,
            global_bounce_rate: 0.1,
            buy_multiple_products: 0.1,
            search_quality: 0.9,
            view_product_to_buy: 0.1,
            refund: 0.0,
            product_rating: 0.9,
        },
        Intention::MakeRefund(_) => Coefficients {
            abandon_cart: 0.,
            cart_completion: 0.,
            discover: 0.,
            search_for_product: 0.,
            go_to_index: 0.1,
            store_navigation_quality: 0.,
            bounce_rate: 0.,
            global_bounce_rate: 0.1,
            buy_multiple_products: 0.,
            search_quality: 0.,
            view_product_to_buy: 0.,
            refund: 1.0,
            product_rating: 0.,
        },
    }
}
