[profile.release]
#lto = "fat"
#codegen-units = 1
#opt-level = 3

[workspace]
members = [
    "src/common",
    "src/contract-test-server",
    "src/demo",
    "src/events-gen",
    "src/metadata",
    "src/platform",
    "src/query",
    "src/service",
    "src/store",
#    "src/ttest"s
]
