[profile.release]
#lto = "fat"
#codegen-units = 1
#opt-level = 3
[workspace]
resolver = "2"
members = [
    "src/common",
    "src/events-gen",
    "src/metadata",
    "src/platform",
    "src/query",
    "src/storage",
    "src/ingester",
    "src/cmd"
    ]
