[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3

[workspace]
members = [
    "src/metadata",
    "src/common",
    "src/query",
    "src/store",
    "src/platform",
    "src/events-gen",
    "src/cmd",
]
