[workspace]
members = [
    "metadata",
    "common",
    "query",
    "store",
    "platform",
    "cmd",
    "arrow-datafusion/datafusion",
    "arrow-datafusion/datafusion-expr",
    "arrow-datafusion/datafusion-common",
    "events-gen",
]
