host = "0.0.0.0:8080"
path = "/tmp/db"
ua_db_path = "init/ingester/regexes.yaml"
geo_city_path = "init/ingester/GeoLite2-City.mmdb"
session_cleaner_interval = "1 second"
project_default_session_duration = "2 days"
access_token_duration = "1 hour"
refresh_token_duration = "24 hours"