[server]
host = "0.0.0.0:8080"

[data]
path = "/tmp/db"
ua_db_path = "init/ingester/regexes.yaml"
geo_city_path = "init/ingester/GeoLite2-City.mmdb"
ui_path = "/Users/maximbogdanov/optiprism/optiprism/frontend/dist"

[misc]
session_cleaner_interval = "1 second"
project_default_session_duration = "1 day"

[auth]
access_token_duration = "1 hour"
refresh_token_duration = "24 hours"

[log]
level = "debug"