[package]
name = "cmd"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
anyhow = "1.0.65"
arrow = { version = "20.0.0", features = ["prettyprint"] }
axum = { version = "0.5.16", features = ["headers"] }
chrono = { version = "0.4.19" }
clap = { version = "4.0.15", features = ["derive"] }
common = { path = "../common" }
contract-test-server = { path = "../contract-test-server" }
crossbeam-channel = "0.3.9"
csv = "1.1"
dateparser = "0.1.7"
demo = { path = "../demo" }
enum-iterator = "1.2.0"
events-gen = { path = "../events-gen" }
futures = "0.3.21"
humantime = "2.1.0"
metadata = { path = "../metadata" }
num_cpus = "1.13.1"
parse_duration = "2.1.1"
platform = { path = "../platform" }
query = { path = "../query" }
rand = "0.8.0"
rust_decimal = { version = "1.22.0", features = ["serde-float"] }
serde = { version = "1.0.133", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.31"
time = "0.1.44"
tokio = { version = "1.15.0", features = ["full"] }
tower = { version = "0.4.11", features = ["util"] }
tower-cookies = "0.7.0"
tower-http = { version = "0.3.4", features = ["add-extension"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[[bin]]
name = "optiprism"
path = "src/main.rs"
