[package]
name = "store"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
anyhow = "1.0.66"
# arrow = "33.0.0"
# arrow-array = "33.0.0"
chrono = { version = "0.4.23", features = ["serde"] }
#parquet = "33.0.0"
thiserror = "1.0.37"
bytes = "1.3.0"
#parquet2 = "0.17.1"
parquet2 = { path = "../../deps/parquet2" }
arrow2 = { path = "../../deps/arrow2" ,features = ["io_parquet","compute_arithmetics"]}
#arrow2 = { version = "0.15.0", features = ["io_parquet","compute_arithmetics"] }

[[bin]]
name = "parquet2"
test = false
bench = false

[[bin]]
name = "parquet"
test = false
bench = false