[package]
name = "store"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[profile.test]
#lto = "fat"
#codegen-units = 1
opt-level = 3

[dependencies]
num-traits = "0.2.15"
#test-log = "0.2.11"
env_logger = "*"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
tracing = "0.1.37"
bitmaps = "3.2.0"
fallible-streaming-iterator = "0.1.9"
ordered-float = "3.4.0"
anyhow = "1.0.66"
arrow = { version = "34.0.0", features = ["ffi"] }
arrow-array = "34.0.0"
arrow-buffer = "34.0.0"
arrow-data = { version = "34.0.0", features = ["ffi"] }
arrow-schema = { version = "34.0.0" }
# arrow = "33.0.0"
# arrow-array = "33.0.0"
chrono = { version = "0.4.23", features = ["serde"] }
#parquet = "33.0.0"
thiserror = "1.0.37"
bytes = "1.3.0"
parquet2 = { git = "ssh://git@github.com/optiprism-io/parquet2.git" }
#parquet2 = { path = "../../../parquet2" }
#arrow2 = { path = "../../../arrow2", features = ["io_print", "io_parquet", "io_csv", "io_json", "compute_arithmetics", "compute_merge_sort", "compute_concatenate"] }
arrow2 = { git = "ssh://git@github.com/optiprism-io/arrow2.git", features = ["io_print", "io_parquet", "io_csv", "io_json", "compute_arithmetics", "compute_merge_sort", "compute_concatenate"] }
rayon = "1.6.1"
futures = "0.3.25"
tracing-test = "0.2.4"

[dev-dependencies]
rstest = "0.17.0"