[package]
name = "store"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
arrow = "20.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
datafusion = "11.0.0"
