[package]
name = "store"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
arrow = "28.0.0"
chrono = { version = "0.4.23", features = ["serde"] }
datafusion = "15.0.0"
