[package]
name = "store"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
arrow = "30.0.1"
chrono = { version = "0.4.23", features = ["serde"] }
parquet = "30.0.1"
thiserror = "1.0.37"
bytes = "1.3.0"
parquet2 = "0.17.1"
arrow2 = { version = "0.15.0", features = ["io_parquet"] }