/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountProjects
 */
export interface AccountProjects {
    /**
     * 
     * @type {number}
     * @memberof AccountProjects
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountProjects
     */
    role?: string;
}
