/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventFilterByCohort } from './event-filter-by-cohort';
import { EventFilterByGroup } from './event-filter-by-group';
import { EventFilterByProperty } from './event-filter-by-property';
/**
 * 
 * @export
 * @interface EventFiltersGroups
 */
export interface EventFiltersGroups {
    /**
     * 
     * @type {string}
     * @memberof EventFiltersGroups
     */
    filtersCondition?: EventFiltersGroupsFiltersConditionEnum;
    /**
     * 
     * @type {Array<EventFilterByCohort | EventFilterByProperty | EventFilterByGroup>}
     * @memberof EventFiltersGroups
     */
    filters?: Array<EventFilterByCohort | EventFilterByProperty | EventFilterByGroup>;
}

/**
    * @export
    * @enum {string}
    */
export enum EventFiltersGroupsFiltersConditionEnum {
    And = 'and',
    Or = 'or'
}

