/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryAggregateProperty } from './query-aggregate-property';
import { QueryAggregatePropertyPerGroup } from './query-aggregate-property-per-group';
import { QueryCountPerGroup } from './query-count-per-group';
import { QueryFormula } from './query-formula';
import { QuerySimple } from './query-simple';
/**
 * event query
 * @export
 * @interface EventQuery
 */
export interface EventQuery {
    /**
     * 
     * @type {string}
     * @memberof EventQuery
     */
    name?: string;
    /**
     * 
     * @type {QuerySimple | QueryCountPerGroup | QueryAggregatePropertyPerGroup | QueryAggregateProperty | QueryFormula}
     * @memberof EventQuery
     */
    query: QuerySimple | QueryCountPerGroup | QueryAggregatePropertyPerGroup | QueryAggregateProperty | QueryFormula;
}
