/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * see https://datatracker.ietf.org/doc/html/rfc7519
 * @export
 * @interface JWTToken
 */
export interface JWTToken {
    /**
     * 
     * @type {number}
     * @memberof JWTToken
     */
    accountId: number;
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    iss: JWTTokenIssEnum;
    /**
     * 
     * @type {number}
     * @memberof JWTToken
     */
    exp: number;
    /**
     * 
     * @type {number}
     * @memberof JWTToken
     */
    nbf: number;
    /**
     * 
     * @type {number}
     * @memberof JWTToken
     */
    iat: number;
    /**
     * 
     * @type {number}
     * @memberof JWTToken
     */
    jti: number;
}

/**
    * @export
    * @enum {string}
    */
export enum JWTTokenIssEnum {
    Optiprism = 'optiprism'
}

