/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum QueryAggregate {
    Sum = 'sum',
    Avg = 'avg',
    Median = 'median',
    Min = 'min',
    Max = 'max',
    DistinctCount = 'distinctCount',
    _25thPercentile = '25thPercentile',
    _75thPercentile = '75thPercentile',
    _90thPercentile = '90thPercentile',
    _99thPercentile = '99thPercentile'
}

