/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrackContext } from './track-context';
/**
 * 
 * @export
 * @interface AliasUserRequest
 */
export interface AliasUserRequest {
    /**
     * 
     * @type {TrackContext}
     * @memberof AliasUserRequest
     */
    context?: TrackContext;
    /**
     * 
     * @type {string}
     * @memberof AliasUserRequest
     */
    alias?: string;
}
