/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrackContextApp } from './track-context-app';
import { TrackContextCampaign } from './track-context-campaign';
import { TrackContextDevice } from './track-context-device';
import { TrackContextLibrary } from './track-context-library';
import { TrackContextLocation } from './track-context-location';
import { TrackContextNetwork } from './track-context-network';
import { TrackContextOs } from './track-context-os';
import { TrackContextPage } from './track-context-page';
import { TrackContextScreen } from './track-context-screen';
/**
 * 
 * @export
 * @interface TrackContext
 */
export interface TrackContext {
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    anonymousId?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TrackContext
     */
    timestamp?: Date;
    /**
     * 
     * @type {TrackContextApp}
     * @memberof TrackContext
     */
    app?: TrackContextApp;
    /**
     * 
     * @type {TrackContextCampaign}
     * @memberof TrackContext
     */
    campaign?: TrackContextCampaign;
    /**
     * 
     * @type {TrackContextDevice}
     * @memberof TrackContext
     */
    device?: TrackContextDevice;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    ip?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    userAgent?: string;
    /**
     * 
     * @type {TrackContextLibrary}
     * @memberof TrackContext
     */
    library?: TrackContextLibrary;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    locale?: string;
    /**
     * 
     * @type {TrackContextLocation}
     * @memberof TrackContext
     */
    location?: TrackContextLocation;
    /**
     * 
     * @type {TrackContextNetwork}
     * @memberof TrackContext
     */
    network?: TrackContextNetwork;
    /**
     * 
     * @type {TrackContextOs}
     * @memberof TrackContext
     */
    os?: TrackContextOs;
    /**
     * 
     * @type {TrackContextPage}
     * @memberof TrackContext
     */
    page?: TrackContextPage;
    /**
     * 
     * @type {TrackContextScreen}
     * @memberof TrackContext
     */
    screen?: TrackContextScreen;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    groupType?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    groupId?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContext
     */
    timezone?: string;
}
