/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TrackContextApp
 */
export interface TrackContextApp {
    /**
     * 
     * @type {string}
     * @memberof TrackContextApp
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextApp
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextApp
     */
    build?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextApp
     */
    namespace?: string;
}
