/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TrackContextDevice
 */
export interface TrackContextDevice {
    /**
     * 
     * @type {string}
     * @memberof TrackContextDevice
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextDevice
     */
    vendor?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextDevice
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextDevice
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextDevice
     */
    platform?: string;
}
