[package]
name = "contract-test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
datafusion = "11.0.0"
platform = { path = "../platform" }
metadata = { path = "../metadata" }
common = { path = "../common" }
tracing = "0.1.37"
chrono = { version = "0.4.19" }
lazy_static = "1.4.0"
arrow = { version = "20.0.0" }
serde_json = "1.0.74"
async-trait = "0.1.58"