[package]
name = "contract-test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
arrow = { version = "20.0.0" }
async-trait = "0.1.58"
chrono = { version = "0.4.19" }
common = { path = "../common" }
datafusion = "11.0.0"
lazy_static = "1.4.0"
metadata = { path = "../metadata" }
platform = { path = "../platform" }
serde_json = "1.0.74"
tracing = "0.1.37"
