/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventSegmentation } from './event-segmentation';
import { FunnelQuery } from './funnel-query';
/**
 * 
 * @export
 * @interface CreateReportRequest
 */
export interface CreateReportRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateReportRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    name: string;
    /**
     * description
     * @type {string}
     * @memberof CreateReportRequest
     */
    description?: string;
    /**
     * 
     * @type {any & EventSegmentation | FunnelQuery}
     * @memberof CreateReportRequest
     */
    report: any & EventSegmentation | FunnelQuery;
}
