/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomEventEvent } from './custom-event-event';
/**
 * Custom Event is an alias to an expression which is used while querying. You can use regular or custom events in expression. You can combine events in expression, you can use filter by properties. 
 * @export
 * @interface CreateCustomEventRequest
 */
export interface CreateCustomEventRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomEventRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomEventRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCustomEventRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Array<CustomEventEvent>}
     * @memberof CreateCustomEventRequest
     */
    events: Array<CustomEventEvent>;
}
