/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateDashboardRequestRows } from './create-dashboard-request-rows';
/**
 * 
 * @export
 * @interface CreateDashboardRequest
 */
export interface CreateDashboardRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDashboardRequest
     */
    tags?: Array<string>;
    /**
     * dashboard name
     * @type {string}
     * @memberof CreateDashboardRequest
     */
    name: string;
    /**
     * description
     * @type {string}
     * @memberof CreateDashboardRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<CreateDashboardRequestRows>}
     * @memberof CreateDashboardRequest
     */
    rows: Array<CreateDashboardRequestRows>;
}
