/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataType } from './data-type';
/**
 * 
 * @export
 * @interface CustomProperty
 */
export interface CustomProperty {
    /**
     * 
     * @type {number}
     * @memberof CustomProperty
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof CustomProperty
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomProperty
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof CustomProperty
     */
    createdBy?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomProperty
     */
    updatedBy?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomProperty
     */
    projectId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CustomProperty
     */
    events?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof CustomProperty
     */
    isSystem?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomProperty
     */
    status?: CustomPropertyStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomProperty
     */
    description?: string;
    /**
     * 
     * @type {DataType}
     * @memberof CustomProperty
     */
    type?: DataType;
    /**
     * 
     * @type {boolean}
     * @memberof CustomProperty
     */
    nullable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomProperty
     */
    isArray?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomProperty
     */
    tags?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum CustomPropertyStatusEnum {
    Enabled = 'enabled',
    Disabled = 'disabled'
}

