/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DashboardPanel
 */
export interface DashboardPanel {
    /**
     * span
     * @type {number}
     * @memberof DashboardPanel
     */
    span: number;
    /**
     * 
     * @type {string}
     * @memberof DashboardPanel
     */
    type: DashboardPanelTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof DashboardPanel
     */
    reportId: number;
}

/**
    * @export
    * @enum {string}
    */
export enum DashboardPanelTypeEnum {
    Report = 'report'
}

