/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardRows } from './dashboard-rows';
/**
 * 
 * @export
 * @interface Dashboard
 */
export interface Dashboard {
    /**
     * dashboard unique id
     * @type {number}
     * @memberof Dashboard
     */
    id?: number;
    /**
     * create date
     * @type {Date}
     * @memberof Dashboard
     */
    createdAt?: Date;
    /**
     * update (once updated)
     * @type {Date}
     * @memberof Dashboard
     */
    updatedAt?: Date;
    /**
     * id of creator User
     * @type {number}
     * @memberof Dashboard
     */
    createdBy?: number;
    /**
     * id of updater User
     * @type {number}
     * @memberof Dashboard
     */
    updatedBy?: number;
    /**
     * project id
     * @type {number}
     * @memberof Dashboard
     */
    projectId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Dashboard
     */
    tags?: Array<string>;
    /**
     * event name. Must be unique among all project events (including custom). The name field is used while events ingesting.
     * @type {string}
     * @memberof Dashboard
     */
    name?: string;
    /**
     * description
     * @type {string}
     * @memberof Dashboard
     */
    description?: string;
    /**
     * 
     * @type {Array<DashboardRows>}
     * @memberof Dashboard
     */
    rows?: Array<DashboardRows>;
}
