/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyFilterOperation } from './property-filter-operation';
import { PropertyRef } from './property-ref';
import { QueryAggregateProperty } from './query-aggregate-property';
import { TimeAfterFirstUse } from './time-after-first-use';
import { TimeBetween } from './time-between';
import { TimeLast } from './time-last';
import { TimeWindowEach } from './time-window-each';
/**
 * aggregate property and compare to value
 * @export
 * @interface DidEventAggregateProperty
 */
export interface DidEventAggregateProperty {
    /**
     * 
     * @type {string}
     * @memberof DidEventAggregateProperty
     */
    propertyName?: string;
    /**
     * 
     * @type {number}
     * @memberof DidEventAggregateProperty
     */
    propertyId?: number;
    /**
     * 
     * @type {string}
     * @memberof DidEventAggregateProperty
     */
    propertyType: DidEventAggregatePropertyPropertyTypeEnum;
    /**
     * 
     * @type {QueryAggregateProperty}
     * @memberof DidEventAggregateProperty
     */
    aggregate: QueryAggregateProperty;
    /**
     * 
     * @type {PropertyFilterOperation}
     * @memberof DidEventAggregateProperty
     */
    operation: PropertyFilterOperation;
    /**
     * one or more values. Doesn't need if operation is \"empty\" or \"exist\"
     * @type {number}
     * @memberof DidEventAggregateProperty
     */
    value?: number;
    /**
     * time frame
     * @type {TimeBetween | TimeLast | TimeAfterFirstUse | TimeWindowEach}
     * @memberof DidEventAggregateProperty
     */
    time: TimeBetween | TimeLast | TimeAfterFirstUse | TimeWindowEach;
}

/**
    * @export
    * @enum {string}
    */
export enum DidEventAggregatePropertyPropertyTypeEnum {
    Event = 'event',
    User = 'user',
    Custom = 'custom'
}

