/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyFilterOperation } from './property-filter-operation';
import { PropertyRef } from './property-ref';
import { QueryAggregate } from './query-aggregate';
import { TimeAfterFirstUse } from './time-after-first-use';
import { TimeBetween } from './time-between';
import { TimeLast } from './time-last';
import { TimeWindowEach } from './time-window-each';
import { Value } from './value';
/**
 * aggregate property and compare to value
 * @export
 * @interface DidEventAggregateProperty
 */
export interface DidEventAggregateProperty extends PropertyRef {
    /**
     * 
     * @type {string}
     * @memberof DidEventAggregateProperty
     */
    type: DidEventAggregatePropertyTypeEnum;
    /**
     * 
     * @type {QueryAggregate}
     * @memberof DidEventAggregateProperty
     */
    aggregate: QueryAggregate;
    /**
     * 
     * @type {PropertyFilterOperation}
     * @memberof DidEventAggregateProperty
     */
    operation: PropertyFilterOperation;
    /**
     * 
     * @type {Value}
     * @memberof DidEventAggregateProperty
     */
    value?: Value;
    /**
     * time frame
     * @type {TimeBetween | TimeLast | TimeAfterFirstUse | TimeWindowEach}
     * @memberof DidEventAggregateProperty
     */
    time: TimeBetween | TimeLast | TimeAfterFirstUse | TimeWindowEach;
}

/**
    * @export
    * @enum {string}
    */
export enum DidEventAggregatePropertyTypeEnum {
    AggregateProperty = 'aggregateProperty'
}

