/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SegmentConditionDidEvent } from './segment-condition-did-event';
import { SegmentConditionFunnel } from './segment-condition-funnel';
import { SegmentConditionHadPropertyValue } from './segment-condition-had-property-value';
import { SegmentConditionHasPropertyValue } from './segment-condition-has-property-value';
/**
 * segment
 * @export
 * @interface EventSegmentationSegment
 */
export interface EventSegmentationSegment {
    /**
     * name of segment
     * @type {string}
     * @memberof EventSegmentationSegment
     */
    name?: string;
    /**
     * array of conditions
     * @type {Array<SegmentConditionHasPropertyValue | SegmentConditionHadPropertyValue | SegmentConditionDidEvent | SegmentConditionFunnel>}
     * @memberof EventSegmentationSegment
     */
    conditions: Array<SegmentConditionHasPropertyValue | SegmentConditionHadPropertyValue | SegmentConditionDidEvent | SegmentConditionFunnel>;
}
