/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * reference to event by its name and type
 * @export
 * @interface EventRef
 */
export interface EventRef {
    /**
     * 
     * @type {string}
     * @memberof EventRef
     */
    eventName?: string;
    /**
     * 
     * @type {number}
     * @memberof EventRef
     */
    eventId?: number;
    /**
     * 
     * @type {string}
     * @memberof EventRef
     */
    eventType?: EventRefEventTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum EventRefEventTypeEnum {
    Custom = 'custom',
    Regular = 'regular'
}

