/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FunnelFrequencyChartType
 */
export interface FunnelFrequencyChartType {
    /**
     * 
     * @type {string}
     * @memberof FunnelFrequencyChartType
     */
    type: FunnelFrequencyChartTypeTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FunnelFrequencyChartTypeTypeEnum {
    Frequency = 'frequency'
}

