/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FunnelConversionStepsChartTypeResponse
 */
export interface FunnelConversionStepsChartTypeResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof FunnelConversionStepsChartTypeResponse
     */
    dimensionHeaders?: Array<string>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof FunnelConversionStepsChartTypeResponse
     */
    dimensions?: Array<Array<string>>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FunnelConversionStepsChartTypeResponse
     */
    metrics?: Array<FunnelConversionStepsChartTypeResponseMetricsEnum>;
    /**
     * 
     * @type {Array<number>}
     * @memberof FunnelConversionStepsChartTypeResponse
     */
    singles?: Array<number>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof FunnelConversionStepsChartTypeResponse
     */
    series?: Array<Array<number>>;
}

/**
    * @export
    * @enum {string}
    */
export enum FunnelConversionStepsChartTypeResponseMetricsEnum {
    AvgTimeToConvert = 'avgTimeToConvert'
}

