/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * search in results
 * @export
 * @interface GroupRecordsListRequestSearch
 */
export interface GroupRecordsListRequestSearch {
    /**
     * 
     * @type {string}
     * @memberof GroupRecordsListRequestSearch
     */
    term?: string;
    /**
     * 
     * @type {Array<string | number>}
     * @memberof GroupRecordsListRequestSearch
     */
    inUserProperties?: Array<string | number>;
}
