/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ListPropertyValuesRequest
 */
export interface ListPropertyValuesRequest {
    /**
     * use event name only with eventType=event|user
     * @type {string}
     * @memberof ListPropertyValuesRequest
     */
    eventName?: string;
    /**
     * use event id only with eventType=custom
     * @type {number}
     * @memberof ListPropertyValuesRequest
     */
    eventId?: number;
    /**
     * 
     * @type {string}
     * @memberof ListPropertyValuesRequest
     */
    eventType?: ListPropertyValuesRequestEventTypeEnum;
    /**
     * use property name only with propertyType=event|user
     * @type {string}
     * @memberof ListPropertyValuesRequest
     */
    propertyName?: string;
    /**
     * use property id only with propertyType=custom
     * @type {number}
     * @memberof ListPropertyValuesRequest
     */
    propertyId?: number;
    /**
     * 
     * @type {string}
     * @memberof ListPropertyValuesRequest
     */
    propertyType?: ListPropertyValuesRequestPropertyTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ListPropertyValuesRequestEventTypeEnum {
    Event = 'event',
    User = 'user',
    Custom = 'custom'
}
/**
    * @export
    * @enum {string}
    */
export enum ListPropertyValuesRequestPropertyTypeEnum {
    Event = 'event',
    User = 'user',
    Custom = 'custom'
}

