/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventRecord } from './event-record';
/**
 * 
 * @export
 * @interface ListEventRecordsResponse
 */
export interface ListEventRecordsResponse {
    /**
     * 
     * @type {Array<EventRecord>}
     * @memberof ListEventRecordsResponse
     */
    events?: Array<EventRecord>;
}
