/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyRef } from './property-ref';
/**
 * 
 * @export
 * @interface ListEventPropertyValues
 */
export interface ListEventPropertyValues extends PropertyRef {
    /**
     * 
     * @type {string}
     * @memberof ListEventPropertyValues
     */
    eventName: string;
}


