/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    createdBy?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    updatedBy?: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    sessionTimeoutSeconds?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Project
     */
    teams?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Project
     */
    users?: Array<number>;
}
