/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * reference to a property by id or name, depends on property type
 * @export
 * @interface PropertyRef
 */
export interface PropertyRef {
    /**
     * 
     * @type {string}
     * @memberof PropertyRef
     */
    propertyName?: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyRef
     */
    propertyId?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyRef
     */
    propertyType: PropertyRefPropertyTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PropertyRefPropertyTypeEnum {
    Event = 'event',
    User = 'user',
    Custom = 'custom'
}

