/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum QueryAggregate {
    Sum = 'sum',
    Avg = 'avg',
    Median = 'median',
    Count = 'count',
    Min = 'min',
    Max = 'max',
    DistinctCount = 'distinctCount',
    Percentile25 = 'percentile25',
    Percentile75 = 'percentile75',
    Percentile90 = 'percentile90',
    Percentile99 = 'percentile99'
}

