/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventSegmentation } from './event-segmentation';
import { FunnelQuery } from './funnel-query';
/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * report unique id
     * @type {number}
     * @memberof Report
     */
    id?: number;
    /**
     * create date
     * @type {Date}
     * @memberof Report
     */
    createdAt?: Date;
    /**
     * update (once updated)
     * @type {Date}
     * @memberof Report
     */
    updatedAt?: Date;
    /**
     * id of creator User
     * @type {number}
     * @memberof Report
     */
    createdBy?: number;
    /**
     * id of updater User
     * @type {number}
     * @memberof Report
     */
    updatedBy?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Report
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    name?: string;
    /**
     * description
     * @type {string}
     * @memberof Report
     */
    description?: string;
    /**
     * 
     * @type {any & EventSegmentation | FunnelQuery}
     * @memberof Report
     */
    report?: any & EventSegmentation | FunnelQuery;
}
