/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    passwordRepeat: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    lastName?: string;
}
