/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * time range between fixed values
 * @export
 * @interface TimeBetween
 */
export interface TimeBetween {
    /**
     * 
     * @type {string}
     * @memberof TimeBetween
     */
    type: TimeBetweenTypeEnum;
    /**
     * start date
     * @type {Date}
     * @memberof TimeBetween
     */
    from: Date;
    /**
     * end date
     * @type {Date}
     * @memberof TimeBetween
     */
    to: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum TimeBetweenTypeEnum {
    Between = 'between'
}

