/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TrackContextPage
 */
export interface TrackContextPage {
    /**
     * 
     * @type {string}
     * @memberof TrackContextPage
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextPage
     */
    referer?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextPage
     */
    search?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextPage
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackContextPage
     */
    url?: string;
}
