/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Value } from './value';
/**
 * 
 * @export
 * @interface UpdateGroupRecordRequest
 */
export interface UpdateGroupRecordRequest {
    /**
     * map of group property name and property value pairs
     * @type {{ [key: string]: Value; }}
     * @memberof UpdateGroupRecordRequest
     */
    properties: { [key: string]: Value; };
}
