/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Update event request
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * event name to display. If empty then name property is used.
     * @type {string}
     * @memberof UpdateEventRequest
     */
    displayName?: string;
    /**
     * description
     * @type {string}
     * @memberof UpdateEventRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    status?: UpdateEventRequestStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEventRequest
     */
    tags?: Array<string>;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateEventRequestStatusEnum {
    Enabled = 'enabled',
    Disabled = 'disabled'
}

