[package]
name = "events-gen"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
arrow = { version = "20.0.0", features = ["prettyprint"] }
chrono = { version = "0.4.19" }
common = { path = "../common" }
csv = "1.1"
cubic_spline = "1.0.0"
futures = "0.3.21"
indicatif = "0.17.1"
lazy_static = "1.4.0"
metadata = { path = "../metadata" }
rand = "0.8.0"
serde = { version = "1.0.133", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.31"
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.37"
