host = "0.0.0.0:8080"
path = "/var/lib/optiprism"
ua_db_path = "/var/lib/optiprism/init/ingester/regexes.yaml"
geo_city_path = "/var/lib/optiprism/init/ingester/GeoLite2-City.mmdb"
ui_path = "/var/lib/optiprism/frontend"
session_cleaner_interval = "1 second"
project_default_session_duration = "2 days"
access_token_duration = "1 hour"
refresh_token_duration = "24 hours"