[package]
name = "metadata"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
arrow = "20.0.0"
async-trait = "0.1.58"
bincode = "1.3.3"
byteorder = "1.4.3"
chrono = { version = "0.4.19", features = ["serde"] }
common = { path = "../common" }
convert_case = "0.5.0"
datafusion = "11.0.0"
datafusion-common = "11.0.0"
futures = "0.3.19"
rocksdb = { version = "0.19.0", features = ["multi-threaded-cf"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
thiserror = "1.0.31"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "sync"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
mockall = "0.11.2"