[server]
host = "0.0.0.0:8080"

[data]
path = "/var/lib/optiprism"
ua_db_path = "/var/lib/optiprism/init/ingester/regexes.yaml"
geo_city_path = "/var/lib/optiprism/init/ingester/GeoLite2-City.mmdb"
ui_path = "/var/lib/optiprism/frontend"

[misc]
session_cleaner_interval = "30 second"
project_default_session_duration = "1 day"

[auth]
access_token_duration = "1 hour"
refresh_token_duration = "24 hours"

[log]
level = "debug"