# Default values for optiprism.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/optiprismio/optiprism
  pullPolicy: Always
  tag: "v0.6.1"

nameOverride: ""
fullnameOverride: ""

configFile: config.toml

serviceAccount:
  create: true
  annotations: { }
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9102"
  prometheus.io/path: "/metrics"

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080
  args:
    - "server"
    - "--config"
    - "/etc/optiprism/config.d/production.toml"

ingress:
  enabled: true
  className: "nginx"
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/issuer: letsencrypt-prod
  }
  hosts:
    - host: demdxx.optiprism.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - demdxx.optiprism.io
      secretName: letsencrypt-prod

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }

storage:
  name: "optiprism"
  storageClassName: "do-block-storage"
  capacity: "15Gi"
  accessMode: "ReadWriteOnce"