/* tslint:disable */
/* eslint-disable */
/**
 * OptiPrism
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@optiprism.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { IdentifyGroupRequest } from '../models';
import { IdentifyUserRequest } from '../models';
import { UpdateGroupRequest } from '../models';
import { UpdateUserRequest } from '../models';
/**
 * IdentifyApi - axios parameter creator
 * @export
 */
export const IdentifyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Identify user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackIdentify: async (organizationId: number, projectId: number, body?: IdentifyUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            if (organizationId === null || organizationId === undefined) {
                throw new RequiredError('organizationId','Required parameter organizationId was null or undefined when calling trackIdentify.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling trackIdentify.');
            }
            const localVarPath = `/organizations/{organization_id}/projects/{project_id}/track/user/identify`
                .replace(`{${"organization_id"}}`, encodeURIComponent(String(organizationId)))
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Identify group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackIdentify_1: async (organizationId: number, projectId: number, body?: IdentifyGroupRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            if (organizationId === null || organizationId === undefined) {
                throw new RequiredError('organizationId','Required parameter organizationId was null or undefined when calling trackIdentify_1.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling trackIdentify_1.');
            }
            const localVarPath = `/organizations/{organization_id}/projects/{project_id}/track/group/identify`
                .replace(`{${"organization_id"}}`, encodeURIComponent(String(organizationId)))
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} groupId 
         * @param {UpdateGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackUpdateGroup: async (organizationId: number, projectId: number, groupId: string, body?: UpdateGroupRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            if (organizationId === null || organizationId === undefined) {
                throw new RequiredError('organizationId','Required parameter organizationId was null or undefined when calling trackUpdateGroup.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling trackUpdateGroup.');
            }
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling trackUpdateGroup.');
            }
            const localVarPath = `/organizations/{organization_id}/projects/{project_id}/track/group/{group_id}`
                .replace(`{${"organization_id"}}`, encodeURIComponent(String(organizationId)))
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"group_id"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} userId 
         * @param {UpdateUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trackUpdateUser: async (organizationId: number, projectId: number, userId: string, body?: UpdateUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            if (organizationId === null || organizationId === undefined) {
                throw new RequiredError('organizationId','Required parameter organizationId was null or undefined when calling trackUpdateUser.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling trackUpdateUser.');
            }
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling trackUpdateUser.');
            }
            const localVarPath = `/organizations/{organization_id}/projects/{project_id}/track/user/{user_id}`
                .replace(`{${"organization_id"}}`, encodeURIComponent(String(organizationId)))
                .replace(`{${"project_id"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IdentifyApi - functional programming interface
 * @export
 */
export const IdentifyApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Identify user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackIdentify(organizationId: number, projectId: number, body?: IdentifyUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await IdentifyApiAxiosParamCreator(configuration).trackIdentify(organizationId, projectId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Identify group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackIdentify_1(organizationId: number, projectId: number, body?: IdentifyGroupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await IdentifyApiAxiosParamCreator(configuration).trackIdentify_1(organizationId, projectId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} groupId 
         * @param {UpdateGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackUpdateGroup(organizationId: number, projectId: number, groupId: string, body?: UpdateGroupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await IdentifyApiAxiosParamCreator(configuration).trackUpdateGroup(organizationId, projectId, groupId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} userId 
         * @param {UpdateUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackUpdateUser(organizationId: number, projectId: number, userId: string, body?: UpdateUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await IdentifyApiAxiosParamCreator(configuration).trackUpdateUser(organizationId, projectId, userId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * IdentifyApi - factory interface
 * @export
 */
export const IdentifyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Identify user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackIdentify(organizationId: number, projectId: number, body?: IdentifyUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return IdentifyApiFp(configuration).trackIdentify(organizationId, projectId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Identify group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {IdentifyGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackIdentify_1(organizationId: number, projectId: number, body?: IdentifyGroupRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return IdentifyApiFp(configuration).trackIdentify_1(organizationId, projectId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update group
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} groupId 
         * @param {UpdateGroupRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackUpdateGroup(organizationId: number, projectId: number, groupId: string, body?: UpdateGroupRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return IdentifyApiFp(configuration).trackUpdateGroup(organizationId, projectId, groupId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user
         * @param {number} organizationId 
         * @param {number} projectId 
         * @param {string} userId 
         * @param {UpdateUserRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trackUpdateUser(organizationId: number, projectId: number, userId: string, body?: UpdateUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return IdentifyApiFp(configuration).trackUpdateUser(organizationId, projectId, userId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IdentifyApi - object-oriented interface
 * @export
 * @class IdentifyApi
 * @extends {BaseAPI}
 */
export class IdentifyApi extends BaseAPI {
    /**
     * 
     * @summary Identify user
     * @param {number} organizationId 
     * @param {number} projectId 
     * @param {IdentifyUserRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdentifyApi
     */
    public async trackIdentify(organizationId: number, projectId: number, body?: IdentifyUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return IdentifyApiFp(this.configuration).trackIdentify(organizationId, projectId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Identify group
     * @param {number} organizationId 
     * @param {number} projectId 
     * @param {IdentifyGroupRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdentifyApi
     */
    public async trackIdentify_1(organizationId: number, projectId: number, body?: IdentifyGroupRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return IdentifyApiFp(this.configuration).trackIdentify_1(organizationId, projectId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update group
     * @param {number} organizationId 
     * @param {number} projectId 
     * @param {string} groupId 
     * @param {UpdateGroupRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdentifyApi
     */
    public async trackUpdateGroup(organizationId: number, projectId: number, groupId: string, body?: UpdateGroupRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return IdentifyApiFp(this.configuration).trackUpdateGroup(organizationId, projectId, groupId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update user
     * @param {number} organizationId 
     * @param {number} projectId 
     * @param {string} userId 
     * @param {UpdateUserRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdentifyApi
     */
    public async trackUpdateUser(organizationId: number, projectId: number, userId: string, body?: UpdateUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return IdentifyApiFp(this.configuration).trackUpdateUser(organizationId, projectId, userId, body, options).then((request) => request(this.axios, this.basePath));
    }
}
