name: Prepate front-end environment
description: Prepate front-end environment
runs:
  using: composite
  steps:
    - name: Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
      working-directory: ./ui
    - name: Get node_modules cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      working-directory: ./ui
    - name: Install
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
      working-directory: ./ui
    - name: Generate TypeScript from OpenAPI
      uses: ./.github/actions/generate-frontend-api
      with:
        input: ./api/openapi.yaml
        output: ./ui/src/api