name: Prepate front-end environment
description:
runs:
  using: composite
  steps:
    - name: Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: Get node_modules cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
    - name: Generate openapi
      uses: ./.github/actions/generate-frontend-api