apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optiprism.fullname" . }}
  labels:
    {{- include "optiprism.labels" . | nindent 4 }}
data:
  config.toml: |-
{{ .Files.Get .Values.configFile | indent 4}}