apiVersion: v1
kind: Service
metadata:
  name: {{ include "optiprism.fullname" . }}
  labels:
    {{- include "optiprism.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9102
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "optiprism.selectorLabels" . | nindent 4 }}
