apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "optiprism.fullname" . }}
  labels:
    {{- include "optiprism.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "optiprism.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "optiprism.fullname" . }}
  minReadySeconds: 1 # by default is 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "optiprism.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "optiprism.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- range .Values.service.args  }}
            - {{ . }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: optiprism
              mountPath: /var/lib/optiprism/data
            - name: config-volume
              mountPath: /etc/config.d/production.toml
              subPath: config.toml
          readinessProbe:
            httpGet:
              path: /api
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: { { include "optiprism.fullname" . } }
  volumeClaimTemplates:
    - metadata:
        name: optiprism
      spec:
        accessModes:
          - {{ .Values.storage.accessMode  }}
        storageClassName: {{ .Values.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.capacity }}