[package]
name = "metadata"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
datafusion = "11.0.0"
datafusion-common = "11.0.0"
common = { path = "../common" }
rocksdb = { version = "0.19.0", features = ["multi-threaded-cf"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
chrono = { version = "0.4.19", features = ["serde"] }
bincode = "1.3.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "sync"] }
arrow = "20.0.0"
futures = "0.3.19"
convert_case = "0.5.0"
byteorder = "1.4.3"
thiserror = "1.0.31"