[package]
name = "ttest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
arrow = { version = "44.0.0", features = ["prettyprint"] }
arrow-row = "44.0.0"
arrow-array = "44.0.0"