[package]
name = "ttest"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oneshot = "0.1.6"
chrono = "0.4.23"
futures = "0.3.28"
itertools = "0.11.0"
rand = "0.8.5"
tokio = { version = "1.23.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
] }
maxminddb = "0.23.0"