[package]
name = "ttest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "49.0.0", features = ["prettyprint"] }
parquet = { version = "49.0.0" }
arrow-array = "49.0.0"