name: Prepate backend environment
description: Prepate backend environment

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-09-10
        override: true
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: .
        key: rust-${{ runner.OS }}
        sharedKey: rust-${{ runner.OS }}