[package]
name = "common"
version = "0.1.0"
edition = "2021"
authors = ["Optiprism <dev@optiprism.io>"]

[dependencies]
datafusion = "11.0.0"
datafusion-common = "11.0.0"
arrow = { version = "20.0.0", features = ["prettyprint"] }
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
lazy_static = "1.4.0"
jsonwebtoken = "7.2.0"
rand = "0.8.4"
thiserror = "1.0.31"