[package]
name = "ingester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
metadata = { path = "../metadata" }

axum = "0.6.20"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
chrono = { version = "0.4.26", features = ["serde"] }
