name: docker

on: pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Generate Access Token
        id: generate_access_token
        run: |
          echo "::set-output name=token::$(gcloud auth print-access-token)"

      - name: Checkout
        uses: actions/checkout@v3
      - run: docker context create mycontext
      - run: docker context use mycontext
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/ui.dev.Dockerfile
          tags: eu.gcr.io/optiprism/ui:${{ github.head_ref }}
          push: true
          username: oauth2accesstoken
          password: ${{ steps.generate_access_token.outputs.token }}