name: Build and push Docker image Test
on: push
#on:
#  workflow_dispatch:
#    inputs:
#      seat:
#        description: 'Seat on cluster'
#        required: true
#        type: choice
#        options:
#          - nikolai-kushner
jobs:
  build-and-push-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: optiprismio
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "{context}/docker/ui/Dockerfile"
          push: true
          tags: optiprismio/ui:${{ steps.branch-name.outputs.current_branch }}


  delopy-on-k8s:
    runs-on: ubuntu-20.04
    steps:
      - uses: danielr1996/envsubst-action@1.0.0
        env:
          IMAGE_REPO: registry.hub.docker.com/optiprismio/ui
          IMAGE_TAG: ${{ steps.branch-name.outputs.current_branch }}
          SEAT: ${{ github.event.inputs.seat }}
        with:
          input: cloud/kubernetes/ui/deployment.tpl.yaml
          output: cloud/kubernetes/ui/deployment.yaml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f cloud/kubernetes/ui/deployment.yaml