name: Quality Assurance

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: ./ui
        run: npm ci

      - name: Lint
        working-directory: ./ui
        run: npm run lint

      - name: Build
        working-directory: ./ui
        run: npm run build
