name: UI Build and Deploy

env:
  PROJECT_ID: optiprism
  SERVICE: ui
  DEV_HOST: dev.optiprism.io

on:
  workflow_dispatch:
    inputs:
      seat:
        description: 'Seat on cluster'
        required: true
        type: choice
        options:
          - nikolai-kushner
      build:
        description: 'release - static files, debug - node server'
        required: true
        type: choice
        options:
          - release
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/session@v0
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker
        run: gcloud session configure-docker

      - name: Build and Push Container
        run: |-
          DOCKER_BUILDKIT=1 docker build -f docker/ui.${{ github.event.inputs.build }}.Dockerfile -t eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      - uses: danielr1996/envsubst-action@1.0.0
        env:
          IMAGE_REPO: eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
          IMAGE_TAG: ${{ github.sha }}
          SEAT: ${{ github.event.inputs.seat }}
        with:
          input: cloud/kubernetes/ui/deployment.tpl.yaml
          output: cloud/kubernetes/ui/deployment.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f cloud/kubernetes/ui/deployment.yaml